### ISSUE TITLE
Dependency Injection wiki page formatting

### ISSUE THREAD

**Issue by jstasiak** [metaperl/python-oop#2]
Hey,

A maintainer of one of the many Python dependency injection frameworks here! (not mentioning which one, because it's irrelevant to the matter)

I think it'd be nice to have all the libraries/frameworks on the https://github.com/metaperl/python-oop/wiki/Dependency-Injection--&--Inversion-of-Control on more equal footing than now – right now two libraries have their own sections (suggesting many things to the readers I imagine) and the rest goes into a list in the "Others" section.

I don't know what's the protocol here and I didn't want to go and edit the page, so I'll just leave a note here. :)

**Comment by metaperl** [comment]
> I think it'd be nice to have all the libraries/frameworks on the https://github.com/metaperl/python-oop/wiki/Dependency-Injection--&--Inversion-of-Control on more equal footing than now

Yes, now the question is: are they all on equal footing? In other words, are some more maintained, more widely used, more useful?

**Comment by metaperl** [comment]
After a bit of detective work, I added a section for the module you maintain:
https://github.com/metaperl/python-oop/wiki/Dependency-Injection--&--Inversion-of-Control#injector

**Comment by jstasiak** [comment]
Hey, I appreciate that, but it wasn't my intention to give Injector its own section and I'm not too comfortable with it being highlighted like this (especially since it seems like it happened at my request, I'm sure you understand my position).

**Comment by metaperl** [comment]
Going back to your initial statement:

> I think it'd be nice to have all the libraries/frameworks on the https://github.com/metaperl/python-oop/wiki/Dependency-Injection--&--Inversion-of-Control on more equal footing than now

In a sense, they deserve to be on equal footing. In another sense, the more actively maintained and promoted ones deserve attention.

Because you took the time to write to me, it's obvious you are a dedicated person who is passionate about this particular discipline and I think you deserve highlighting.

But I can give you editor rights and you can reformat the whole section to be more democratic... but in doing so, some will be listed earlier than others. And just as people tend to buy things at eye-level in a grocery store and dont notice the things on the bottom shelf, the earlier listed one will be the first to be sampled.

Perhaps some objective measure of quality can be in place. Such as last update or repo. Number of stars on repo... but all of those have drawbacks.
